version: 4

networks:
  arbitrum:
    rpcs:
      - https://arbitrum-one-rpc.publicnode.com
    chain-id: 42161
    network-id: 42161
    currency: ETH
  polygon:
    rpcs:
      - https://polygon-rpc.com
    chain-id: 137
    network-id: 137
    currency: POL
  base:
    rpcs:
      - https://base-rpc.publicnode.com
    chain-id: 8453
    network-id: 8453
    currency: ETH

subgraphs:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/2025-10-11-a62b/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-matic/2025-09-23-7ac3/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-arbitrum-one/2025-09-18-da5d/gn

metaboards:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-base/2025-07-06-594f/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-polygon/0.1/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-arbitrum-one/2025-07-06-135f/gn

orderbooks:
  base:
    address: 0x52CEB8eBEf648744fFDDE89F7Bc9C3aC35944775
    network: base
    subgraph: base
    deployment-block: 36667253
    local-db-remote: raindex
  polygon:
    address: 0x8a3C8E610d827093F7437E0C45EFa648563c0dDA
    network: polygon
    subgraph: polygon
    deployment-block: 76772162
    local-db-remote: raindex
  arbitrum:
    address: 0x8df8075e4077dabf1e95f49059e4c1eea33094ab
    network: arbitrum
    subgraph: arbitrum
    deployment-block: 380203894
    local-db-remote: raindex

deployers:
  base:
    address: 0x6557778Db274f04B9E9f39F8Ff2D621c2036e978
    network: base
  polygon:
    address: 0x6B36e02409BD60cA5C17049c7188de180857902D
    network: polygon
  arbitrum:
    address: 0xb1869a4FA6436832bb0AD5420170B8CF17CaF934
    network: arbitrum

local-db-remotes:
  # raindex: https://pub-7ff233ca8f114c74a2796a803ef8c1bb.r2.dev/manifest.yaml
  raindex: https://raw.githubusercontent.com/findolor/local_db_remote/d03e0263d837ccdd42f708043788ec19cdd200f1/test-manifest.yaml

local-db-sync:
  base:
    batch-size: 10000
    max-concurrent-batches: 15
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 50
    bootstrap-block-threshold: 10000
  polygon:
    batch-size: 10000
    max-concurrent-batches: 15
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 50
    bootstrap-block-threshold: 10000
  arbitrum:
    batch-size: 10000
    max-concurrent-batches: 15
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 50
    bootstrap-block-threshold: 10000
